module.exports = {
  accessoryIcon: './assets/accessory-icon.png',
  armorIcon: './assets/armor-icon.png',
  cardStatArmor: './assets/cardstat-armor.png',
  cardStatAttack: './assets/cardstat-attack.png',
  cardStatGoldCost: './assets/cardstat-goldcost.png',
  cardStatHealth: './assets/cardstat-health.png',
  consumableIcon: './assets/consumable-icon.png',
  cooldownIcon: './assets/cooldown-icon.png',
  creepIcon: './assets/creep-icon.png',
  heroIcon: './assets/hero-icon.png',
  iconBackground: './assets/icon-background.png',
  improvementIcon: './assets/improvement-icon.png',
  initiativeIcon: './assets/initiative-icon.png',
  spellIcon: './assets/spell-icon.png',
  textBackground: './assets/text-background.png',
  weaponIcon: './assets/weapon-icon.png',
};
