module.exports = {
  accessoryIcon: './assets/images/accessory-icon.png',
  armorIcon: './assets/images/armor-icon.png',
  cardStatArmor: './assets/images/cardstat-armor.png',
  cardStatAttack: './assets/images/cardstat-attack.png',
  cardStatGoldCost: './assets/images/cardstat-goldcost.png',
  cardStatHealth: './assets/images/cardstat-health.png',
  consumableIcon: './assets/images/consumable-icon.png',
  cooldownIcon: './assets/images/cooldown-icon.png',
  creepIcon: './assets/images/creep-icon.png',
  heroIcon: './assets/images/hero-icon.png',
  iconBackground: './assets/images/icon-background.png',
  improvementIcon: './assets/images/improvement-icon.png',
  initiativeIcon: './assets/images/initiative-icon.png',
  spellIcon: './assets/images/spell-icon.png',
  textBackground: './assets/images/text-background.png',
  weaponIcon: './assets/images/weapon-icon.png',
};
